### ISSUE TITLE
Feature request: handle symlinked files & folders

### ISSUE THREAD

**Issue by syphernl** [pvizeli/securetar#40]
It seems that if a folder to be packed up contains a symlink (either file or folder), it is added as such. Is there a way to have it include the actual file/folder instead?

## Context
Restoring a HASS backup to a fresh installation broke that installation since the backup contained symlinks of folders and files including `configuration.yaml` causing HASS to not start anymore.

**Comment by agners** [comment]
So you would like that the backup resolves the symlinks, and actually stores the actual file/directory?

I think not all users might be happy with this, some might want to use symlinks within the config folder, or manage the configuration or part of it externally.

**Comment by syphernl** [comment]
It could always be made optional and turned off by-default.

**Comment by pvizeli** [comment]
Feature request of HA please into HA channels
